[package]
name = "p2"
version = "0.1.0"
authors = ["Sebastian Ã…kerman <sebastian.akerman@omegapoint.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
